locals {
  resource_group_hub_name       = "${var.prefix}-hub"
  resource_group_spoke_name     = "${var.prefix}-spoke"
  resource_group_deploy_name    = "${var.prefix}-deploy"
  vnet_hub_name                 = "${var.prefix}-hub-vnet"
  vnet_spoke_name               = "${var.prefix}-spoke-vnet"
  vnet_hub_iprange              = "10.0.0.0/16"
  vnet_spoke_iprange            = "10.1.0.0/16"
  windows_runner_subnet         = "win-runner"
  windows_runner_iprange        = "10.0.0.0/24"
  linux_runner_subnet           = "tux-runner"
  linux_runner_iprange          = "10.0.1.0/24"
  storage_subnet                = "storage"
  storage_subnet_iprange        = "10.1.0.0/24"
  hub_to_spoke_vnet_peer        = "${var.prefix}-hub-spoke-peer"
  spoke_to_hub_vnet_peer        = "${var.prefix}-spoke-hub-peer"
  storage_container_name        = "demo"
  storage_private_endpoint      = "${var.prefix}-storage-pe"
  storage_private_link          = "${var.prefix}-storage-pl"
  deploy_storage_container_name = "deploy"
  storage_blob_dns_zone         = "privatelink.blob.core.windows.net"
  storage_dns_link_spoke        = "${var.prefix}-storage-dns-spoke-link"
  storage_dns_link_hub          = "${var.prefix}-storage-dns-hub-link"
  windows_runner_user_name      = "AzureAdmin"
  windows_runner_internal_nic   = "${var.prefix}-win-nic"
  windows_runner_name           = "${var.prefix}-win"
  windows_runner_disk           = "${var.prefix}-disk"

  linux_runner_internal_nic   = "${var.prefix}-tux-nic"
  linux_runner_name           = "${var.prefix}-tux"
  linux_runner_disk           = "${var.prefix}-tux-disk"

}